#=======================================================================
# Copyright (c) 2017-2020 Aarna Networks, Inc.
# All rights reserved.
# ======================================================================
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#           http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================  
apiVersion: v1
kind: ConfigMap
metadata:
        name: middleend-config
data:
  middleend.conf: |-
    {
      "ownport": "{{ .Values.service.internalPort }}",
      "orchestrator": "orchestrator.{{ .Values.namespace }}.svc.cluster.local:9015",
      "clm": "clm.{{ .Values.namespace }}.svc.cluster.local:9061",
      "ovnaction": "ovnaction.{{ .Values.namespace }}.svc.cluster.local:9051",
      "configSvc": "configsvc.{{ .Values.namespace }}.svc.cluster.local.9082",
      "issuer": "{{ .Values.authproxy.issuer }}",
      "redirect_uri": "{{ .Values.authproxy.redirect_uri }}",
      "client_id": "{{ .Values.authproxy.client_id }}",
      "mongo": "mongo.{{ .Values.namespace }}.svc.cluster.local:27017",
      "logLevel": "{{ .Values.logLevel }}"
    }   
